server:
  port: 8761

eureka:
  client:
    fetch-registry: false #I don't want to fetch any registry from any other eureka server on the network
    register-with-eureka: false # register with eureka false